version: '3'
services:
  node-exporter:
    network_mode: host  # teh default port is 9100
    pid: host
    #    volumes:
    #      - '/:/host:ro,rslave'
    image: 'quay.io/prometheus/node-exporter:latest'

  prometheus:
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - '/usr/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml' #modify the path for local install location
    image: prom/prometheus
    depends_on:
      - node-exporter

  grafana:
    container_name: grafana
    ports:
      - "3457:3000"
    image: grafana/grafana
    depends_on:
      - node-exporter
      - prometheus

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: anniegavr
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - collabbuddy
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - collabbuddy
    restart: unless-stopped

  cache:
    build:
      context: ./cache
      dockerfile: Dockerfile
    image: cache
    container_name: cache
    ports:
      - "8084:8084"
    networks:
      - collabbuddy

  eureka-server:
    image: anniegavr/eureka_server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - collabbuddy
  api-gateway:
    image: anniegavr/api_gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - collabbuddy
    depends_on:
      - eureka-server
  base-service:
    image: anniegavr/base-service:latest
    container_name: base-service
    ports:
      - "8079:8079"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - collabbuddy
    depends_on:
      - eureka-server
      - api-gateway
  schedule-service:
    image: anniegavr/schedule-service:latest
    container_name: schedule-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - collabbuddy
    depends_on:
      - eureka-server
      - api-gateway

networks:
  collabbuddy:
    driver: bridge

volumes:
  postgres:
  pgadmin:
