server:
  port: 8083

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      default-filters:
#        - SaveSession
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 10
#            redis-rate-limiter.burstCapacity: 20
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: service
          uri: lb://BASE-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: baseServiceCircuitBreaker
                fallbackURI: forward:/base-service-fallback
        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/api/v1/schedule/**
          filters:
            - name: CircuitBreaker
              args:
                name: scheduleServiceCircuitBreaker
                fallbackURI: forward:/schedule-service-fallback
#  lifecycle:
#    timeout-per-shutdown-phase: 20s
#    redis:
#      connect-timeout: 30s
#      host: localhost
#      port: 6379
#      timeout: 500ms
#    session:
#      store-type: redis
#      timeout: 10m
#      redis:
#        namespace: library:gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always