global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.108:9090'] ## IP Address of the localhost. Must match the port to the dedicated container port
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.108:9100'] ## IP Address of the localhost
